name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-name: [faker-register-test, cart-persistent-test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress E2E Test - ${{ matrix.test-name }}
        id: cypress-tests
        run: npm run ${{ matrix.test-name }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Debug what files are actually being generated
      - name: Debug report directory structure
        if: always()
        run: |
          echo "Contents of cypress/reports:"
          find cypress/reports -type f | sort
      
      - name: Upload Individual Test Report
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.test-name }}
          path: cypress/reports/
          retention-days: 30

  # Simplified report consolidation approach
  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Create reports directory
      - name: Create reports directory
        run: mkdir -p cypress/reports/merged
      
      # Download all artifacts at once
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: temp-artifacts
      
      # Debug what was downloaded
      - name: Show artifact contents
        run: |
          echo "Downloaded artifacts:"
          find temp-artifacts -type f | sort
      
      # Process the reports - adapt this to match your actual report structure
      - name: Process reports
        run: |
          # Create directories for each test
          mkdir -p cypress/reports/merged/faker-register-test
          mkdir -p cypress/reports/merged/cart-persistent-test
          
          # See what HTML files we have and copy them to appropriate locations
          if [ -d "temp-artifacts/report-faker-register-test" ]; then
            # Find all HTML files for faker test
            find temp-artifacts/report-faker-register-test -name "*.html" -type f -exec cp {} cypress/reports/merged/faker-register-test/ \;
            # If there's an index.html in any subdirectory, copy it specifically
            find temp-artifacts/report-faker-register-test -name "index.html" -type f -exec cp {} cypress/reports/merged/faker-register-test/ \;
          fi
          
          if [ -d "temp-artifacts/report-cart-persistent-test" ]; then
            # Find all HTML files for cart test
            find temp-artifacts/report-cart-persistent-test -name "*.html" -type f -exec cp {} cypress/reports/merged/cart-persistent-test/ \;
            # If there's an index.html in any subdirectory, copy it specifically
            find temp-artifacts/report-cart-persistent-test -name "index.html" -type f -exec cp {} cypress/reports/merged/cart-persistent-test/ \;
          fi
          
          # Create index files if they don't exist
          if [ ! -f "cypress/reports/merged/faker-register-test/index.html" ]; then
            echo "<html><body><h1>Faker Register Test Report</h1><p>No HTML report found</p></body></html>" > cypress/reports/merged/faker-register-test/index.html
          fi
          
          if [ ! -f "cypress/reports/merged/cart-persistent-test/index.html" ]; then
            echo "<html><body><h1>Cart Persistent Test Report</h1><p>No HTML report found</p></body></html>" > cypress/reports/merged/cart-persistent-test/index.html
          fi
      
      # Create a main index file
      - name: Generate main index.html
        run: |
          cat << EOF > cypress/reports/merged/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <title>Cypress Test Reports</title>
            <style>
              body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
              h1 { color: #333366; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 10px 0; padding: 15px; background-color: #f5f5f5; border-radius: 5px; }
              a { color: #0066cc; text-decoration: none; font-weight: bold; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>Cypress Test Reports</h1>
            <ul>
              <li><a href="faker-register-test/index.html">Faker Register Test Report</a></li>
              <li><a href="cart-persistent-test/index.html">Cart Persistent Test Report</a></li>
            </ul>
            <p>Generated on $(date)</p>
          </body>
          </html>
          EOF
      
      # Debug the final merged directory structure
      - name: Show final structure
        run: |
          find cypress/reports/merged -type f | sort
      
      # Deploy to GitHub Pages
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: cypress/reports/merged/
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4